//HintName: TestQueryPipeline.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoCQRS.Generators
// Version: {Removed}
// </auto-generated>
namespace Examples
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class TestQueryPipeline
    {
        private readonly global::Examples.TestQueryHandler1 _testQueryHandler1;
        private readonly global::Examples.TestQueryHandler2 _testQueryHandler2;
        private readonly global::Examples.TestQueryHandler3 _testQueryHandler3;

        public TestQueryPipeline(global::Examples.ExampleSevice1 exampleSevice1, global::Examples.ExampleSevice2 exampleSevice2, global::Examples.ExampleSevice3 exampleSevice3)
        {
            _testQueryHandler1 = new global::Examples.TestQueryHandler1(exampleSevice1);
            _testQueryHandler2 = new global::Examples.TestQueryHandler2(exampleSevice2);
            _testQueryHandler3 = new global::Examples.TestQueryHandler3(exampleSevice2, exampleSevice3);
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<int> Handle(global::Examples.TestQuery item, [global::System.Runtime.CompilerServices.EnumeratorCancellationAttribute] global::System.Threading.CancellationToken cancellation)
        {
            yield return await _testQueryHandler1.Handle(item, cancellation);
            yield return await _testQueryHandler2.Handle(item, cancellation);
            yield return await _testQueryHandler3.Handle(item, cancellation);
        }
    }
}