//HintName: TestCommandPipeline.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoCQRS.Generators
// Version: {Removed}
// </auto-generated>
namespace Examples
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class TestCommandPipeline
    {
        private readonly global::Examples.TestCommandHandler1 _testCommandHandler1;
        private readonly global::Examples.TestCommandHandler2 _testCommandHandler2;
        private readonly global::Examples.TestCommandHandler3 _testCommandHandler3;

        public TestCommandPipeline()
        {
            _testCommandHandler1 = new global::Examples.TestCommandHandler1();
            _testCommandHandler2 = new global::Examples.TestCommandHandler2();
            _testCommandHandler3 = new global::Examples.TestCommandHandler3();
        }

        public async global::System.Collections.Generic.IAsyncEnumerable<int> Handle(global::Examples.TestCommand item, [global::System.Runtime.CompilerServices.EnumeratorCancellationAttribute] global::System.Threading.CancellationToken cancellation)
        {
            yield return await _testCommandHandler1.Handle(item, cancellation);
            yield return await _testCommandHandler2.Handle(item, cancellation);
            yield return await _testCommandHandler3.Handle(item, cancellation);
        }
    }
}